from marshmallow import Schema, fields

# Marshmallow şeması
class IlandetailSchema(Schema):
    url = fields.Str(required=True)
    baslik = fields.Str(required=True)
    fiyat = fields.Str(required=True)
    konum = fields.Str(required=True)
    Ilan_Numarasi = fields.Str(required=True)
    İlan_Oluşturma_Tarihi = fields.Str(allow_none=True)
    İlan_Güncelleme_Tarihi = fields.Str(allow_none=True)
    Kategorisi = fields.Str(allow_none=True)
    Net_Metrekare = fields.Str(allow_none=True)
    Oda_Sayısı = fields.Str(allow_none=True)
    Bulunduğu_Kat = fields.Str(allow_none=True)
    Isıtma_Tipi = fields.Str(allow_none=True)
    Kullanım_Durumu = fields.Str(allow_none=True)
    Yapı_Tipi = fields.Str(allow_none=True)
    Site_İçerisinde = fields.Str(allow_none=True)
    Banyo_Sayısı = fields.Str(allow_none=True)
    WC_Sayısı = fields.Str(allow_none=True)
    Türü = fields.Str(allow_none=True)
    Tipi = fields.Str(allow_none=True)
    Brüt_Metrekare = fields.Str(allow_none=True)
    Binanın_Yaşı = fields.Str(allow_none=True)
    Binanın_Kat_Sayısı = fields.Str(allow_none=True)
    İzin_Belge_No = fields.Str(allow_none=True)
    Yapı_Durumu = fields.Str(allow_none=True)
    Eşya_Durumu = fields.Str(allow_none=True)
    Takas = fields.Str(allow_none=True)
    Salon_Metrekare = fields.Str(allow_none=True)
    Fiyat_Durumu = fields.Str(allow_none=True)